baseurl = "https://github.com/sarbearschwartz/hugo-universal-theme" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Sarah Schwartz Stats"
theme = "hugo-universal-theme"
themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false




# Main menu

[menu]


# (1) -------- Home --------

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1





# (2) -------- Teaching --------

[[menu.main]]
    name = "Teaching"
    identifier = "menu.teaching"
    url        = "/img/hex/Superman_R_logo.PNG"
    weight     = 3


# (2-A) Teaching - USU Grad Courses

[[menu.main]]
    name       = "USU Grad Courses"
    identifier = "section.course"
    url        = ""
    weight     = 1
    parent     = "menu.teaching"
    post       = 1
    

[[menu.main]]
    name       = "6600 Foundation"
    url        = ""
    weight     = 1
    parent     = "section.course"    
    
[[menu.main]]
    name       = "7610 Regression"
    url        = ""
    weight     = 2
    parent     = "section.course"      
    
[[menu.main]]
    name       = "7650 Multilevel"
    url        = ""
    weight     = 3
    parent     = "section.course" 



# (2-B) Teaching - USU Workshops

[[menu.main]]
    name       = "USU Workshops"
    identifier = "section.workshops"
    url        = ""
    weight     = 2
    parent     = "menu.teaching"
    post       = 2


[[menu.main]]
    name       = "R for Reseach: Intro"
    url        = ""
    weight     = 1
    parent     = "section.workshops" 

[[menu.main]]
    name       = "R for Reseach: Intermediate"
    url        = ""
    weight     = 2
    parent     = "section.workshops" 







# (3) -------- Portfolio --------

[[menu.main]]
    name       = "Portfolio"
    identifier = "menu.portfolio"
    url        = "/img/hex/hex_headshot.png"
    weight     = 3


# (3-A) Portfolio - Pubs

[[menu.main]]
    name       = "Pubilcations"
    identifier = "section.pubs"
    weight     = 1
    parent     = "menu.portfolio"
    post       = 1
    
# (3-A) Portfolio - Docs    
    

[[menu.main]]
    name       = "Documents"
    identifier = "section.docs"
    weight     = 2
    parent     = "menu.portfolio"
    post       = 2








# (4) -------- eBooks --------

[[menu.main]]
    name       = "eBooks"
    identifier = "menu.eBooks"
    url        = "/img/hex/hex_eBooks.png"
    weight     = 4
    
    
# (4-A) Portfolio - Encyclopedia

[[menu.main]]
    name       = "Quantitative Methods in R"
    identifier = "section.ency"
    weight     = 1
    parent     = "menu.eBooks"
    post       = 1






# (5) -------- Blog --------

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5


# (6) -------- FAQ --------

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6


# (7) -------- Contact --------

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7




# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+435 797 0169"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/sarbearschwartz"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:sarah.schwartz@usu.edu"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    #facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    #twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    #default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    #enableGoogleMaps = true
    #googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    #latitude = "-12.043333"
    #longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    #formspree_action = "https://formspree.io/sample/of/endpoint"
    #contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    #enableRecaptchaInContactForm = false
    #googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>This is my ABOIT statement.</p>"
    copyright = "Copyright (c) 2024 - 2025, Sarah Schwartz Stats; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Sarah Schwartz Stats"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Utah State University</strong>
        <br>Education Building, Room 455
        <br>2800 Old Main Hill
        <br>Logan, UT 84322-2800
        <br>USA
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact me at sarah.schwartz@usu.edu</p>
      <p class="hidden-md hidden-lg"><a href="tel:435-797-0169" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:sarah.schwartz@usu.edu" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

#[params.carouselCustomers]
#    items = 6
#    auto_play = false
#    slide_speed = 2000
#    pagination_speed = 1000

[params.carouselTeaching]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

#[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    #enable = true
    #auto_play = true
    #slide_speed = 2000
    #pagination_speed = 1000

#[params.features]
#    enable = true
#    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.teaching]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Teaching"
    subtitle = "Teaching Focus for the 2024-2025 School Year"

#[params.see_more]
#    enable = true
#    icon = "far fa-file-alt"
#    title = "Do you want to see more?"
#    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
#    link_url = "#"
#    link_text = "Check other homepages"

#[params.clients]
#    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
#    title = "Our Clients"
#    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Stats in Action?"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
