---
title: "Teaching Experience"
about: 
    template: solana
---

# Philosophy

-   Growth mindset

-   Application

    ------------------------------------------------------------------------

# Graduate Course

Currently teaching at USU

::: {.panel-tabset .nav-pills}
## Using R

EDUC

### Introduction to Using R for Research

Workshop Series

## Foundations

PSY 6600 or EDUC 6600

### Statistical Foundations

This course covers research design and statistical concepts for research in education, human services, and psychology, with an emphasis on the selection and interpretation of statistical analyses.

## Regression

PSY 7610 or EDUC 7610

### Regression Analysis

This course is an advanced treatment of research design and statistical concepts and issues in educational, human services, and psychological research.

## Multilevel

PSY 7650

### Multilevel and Marginal Models

Coverage of multilevel (i.e., mixed-effects, hierarchical linear), and marginal (GEE) models for both continuous and categorical outcomes. Includes application of these methods to many types of cross-sectional and longitudinal research designs (e.g., experimental, case-control, cohort, cross-over, complex sample, randomized controlled trials).
:::

------------------------------------------------------------------------

# Undergraduate Courses

Past courses taught at USU

::: {.panel-tabset .nav-pills}
## PSY 3010

### Psychological Statistics

This course is an introduction to descriptive and inferential statistics for the behavioral sciences. Topics include measures of central tendency and variability, sampling distributions, and hypothesis testing procedures including t-tests, analysis of variance, and correlation and regression.

## STAT 2000

### Statistical Methods

Introduction to statistical concepts, graphical techniques, probability, distributions, estimation, one and two sample testing, chi-square tests, and simple linear regression, one-way ANOVA.

## STAT 1040

### Introduction to Statistics

Descriptive and inferential statistical methods. Emphasis on conceptual understanding and statistical thinking. Examples presented from many different areas.

## MATH 1050

### College Algebra

Functions: graphs, transformations, combinations and inverses. Polynomial, rational, exponential, logarithmic functions and applications. Systems of equations and matrices. Graphing calculator required.

## MATH 1010

### Intermediate Algebra

Linear equations and inequalities, polynomials and exponents, rational expressions, roots and radicals, quadratic equations, lines, systems of equations and inequalities, applied problems , factoring, graphs, the quadratic formula , completing the square and complex numbers.
:::
