---
title: "Hex Stickers"
author: "Dr. Sarah Schwartz"
output: html_notebook
---


```{r}
library(tidyverse)
library(hexSticker)
```




```{r, fig.width=4, fig.height=4}
p <- PlantGrowth %>% 
  dplyr::filter(!(group == "trt1" & weight > 5.5)) %>% 
  ggplot(aes(x = group,
             y = weight,
             fill = group)) +
  geom_boxplot(color = "#FFFFFF",
               size = .25)  +
  labs(x = NULL,
       y = NULL) 

p + theme_dark()
```

```{r}
p <- p +
  theme_void() +
  theme_transparent() +
  theme(legend.position = "none")

p %>% 
  hexSticker::sticker(package  ="EDUC/PSY 6600", 
                      p_size   = 15, 
                      p_color  = "#FFFFFF",
                      url      = "Statistical Foundations",
                      u_size   = 6.75,
                      u_color  = "#FFFFFF",
                      s_x      = 1, 
                      s_y      = .75, 
                      s_width  = 1.3, 
                      s_height = 1,
                      h_fill   = "#0F2439",
                      h_color  = "#8A8D8F",
                      filename = "hex_6600.png")
```





